const API_MESSAGES = {
  ko: {
    loadProducts: '상품 목록을 불러오지 못했습니다.',
    searchProducts: '상품 검색에 실패했습니다.',
    loadProductInfo: '상품 정보를 불러오지 못했습니다.',
    imageUploadFailed: '이미지 업로드에 실패했습니다.',
    categoryRequired: '카테고리는 필수입니다.',
    productPhotoRequired: '상품 사진은 필수입니다.',
    productSubmitFailed: '상품 등록에 실패했습니다.',
    productSubmitNoProduct: '상품 등록 결과를 받지 못했습니다.',
    metadataFromUrlFailed: 'URL에서 정보를 추출하지 못했습니다.',
    metadataFromImageFailed: '이미지에서 정보를 추출하지 못했습니다.',
    sizeTableExtractFailed: '사이즈표를 추출하지 못했습니다.',
    sizeTableNormalizeFailed: '추출한 사이즈표를 정리하지 못했습니다.',
    closetLoadFailed: '옷장을 불러오지 못했습니다.',
    closetAddFailed: '옷장에 추가하지 못했습니다.',
    closetRemoveFailed: '옷장에서 제거하지 못했습니다.',
    mySizeCreateFailed: '내 사이즈 등록에 실패했습니다.',
    mySizeUpdateFailed: '내 사이즈 수정에 실패했습니다.',
    mySizeDeleteFailed: '내 사이즈 삭제에 실패했습니다.',
    digboxLoadFailed: '저장 목록을 불러오지 못했습니다.',
    digboxAddFailed: '저장하지 못했습니다.',
    digboxRemoveFailed: '저장 해제하지 못했습니다.',
    accountDeleteFailed: '계정 삭제에 실패했습니다.',
    cleanupFailed: '미완료 가입 정리에 실패했습니다.',
    profileCompleteFailed: '프로필 설정을 완료하지 못했습니다.',
    usernameAvailabilityFailed: '사용자 이름을 확인하지 못했어요.',
    usernameSuggestionsFailed: '추천 사용자 이름을 불러오지 못했어요.',
    usernameChangeFailed: '사용자 이름을 변경하지 못했어요.',
    outfitRequestsLoadFailed: '요청을 처리하지 못했습니다.',
    tasteAnalysisLoadFailed: '취향 분석을 불러오지 못했습니다.',
    digboxSizeDecisionSaveFailed: '사이즈 기록 저장 실패',
  },
  en: {
    loadProducts: "We couldn't load the product list.",
    searchProducts: "Product search failed.",
    loadProductInfo: "We couldn't load product information.",
    imageUploadFailed: "Image upload failed.",
    categoryRequired: "Category is required.",
    productPhotoRequired: "A product photo is required.",
    productSubmitFailed: "Product submission failed.",
    productSubmitNoProduct: "Product submission returned no product.",
    metadataFromUrlFailed: "Failed to extract metadata from URL.",
    metadataFromImageFailed: "Failed to extract metadata from image.",
    sizeTableExtractFailed: "Failed to extract size table.",
    sizeTableNormalizeFailed: "Failed to normalize extracted size table.",
    closetLoadFailed: "Failed to load closet.",
    closetAddFailed: "Failed to add to closet.",
    closetRemoveFailed: "Failed to remove from closet.",
    mySizeCreateFailed: "Failed to create My Size.",
    mySizeUpdateFailed: "Failed to update My Size.",
    mySizeDeleteFailed: "Failed to delete My Size.",
    digboxLoadFailed: "Failed to load saved products.",
    digboxAddFailed: "Failed to save.",
    digboxRemoveFailed: "Failed to remove from saved.",
    accountDeleteFailed: "Failed to delete account.",
    cleanupFailed: "Failed to clean up incomplete signup.",
    profileCompleteFailed: "Failed to complete profile.",
    usernameAvailabilityFailed: "We couldn't check your username.",
    usernameSuggestionsFailed: "We couldn't load suggested usernames.",
    usernameChangeFailed: "We couldn't change your username.",
    outfitRequestsLoadFailed: "We couldn't process the request.",
    tasteAnalysisLoadFailed: "We couldn't load your taste analysis.",
    digboxSizeDecisionSaveFailed: "Failed to save size decision",
  },
} as const;

type ApiMessageKey = keyof typeof API_MESSAGES.ko;

export function apiMessage(key: ApiMessageKey): string {
  const isEnglish = typeof document !== "undefined" && document.documentElement.lang === "en";
  return (isEnglish ? API_MESSAGES.en : API_MESSAGES.ko)[key];
}
